// This file is auto-generated by @hey-api/openapi-ts

export const AIFixSuggestionPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        violation_id: {
            type: 'string',
            format: 'uuid',
            title: 'Violation Id'
        },
        provider: {
            $ref: '#/components/schemas/AIProviderName'
        },
        model: {
            type: 'string',
            title: 'Model'
        },
        suggestion: {
            type: 'string',
            title: 'Suggestion'
        },
        prompt_tokens: {
            type: 'integer',
            title: 'Prompt Tokens'
        },
        completion_tokens: {
            type: 'integer',
            title: 'Completion Tokens'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'id',
        'violation_id',
        'provider',
        'model',
        'suggestion',
        'prompt_tokens',
        'completion_tokens',
        'created_at'
    ],
    title: 'AIFixSuggestionPublic'
} as const;

export const AIProviderNameSchema = {
    type: 'string',
    enum: [
        'openai',
        'anthropic',
        'google',
        'ollama'
    ],
    title: 'AIProviderName'
} as const;

export const AnalysisReportPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        repository_id: {
            type: 'string',
            format: 'uuid',
            title: 'Repository Id'
        },
        trigger_type: {
            $ref: '#/components/schemas/TriggerType'
        },
        trigger_ref: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Trigger Ref'
        },
        status: {
            $ref: '#/components/schemas/AnalysisStatus'
        },
        total_violations: {
            type: 'integer',
            title: 'Total Violations'
        },
        violations_by_severity: {
            additionalProperties: true,
            type: 'object',
            title: 'Violations By Severity'
        },
        score: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Score'
        },
        grade: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grade'
        },
        error_message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Message'
        },
        started_at: {
            type: 'string',
            format: 'date-time',
            title: 'Started At'
        },
        completed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Completed At'
        }
    },
    type: 'object',
    required: [
        'id',
        'repository_id',
        'trigger_type',
        'trigger_ref',
        'status',
        'total_violations',
        'violations_by_severity',
        'score',
        'grade',
        'error_message',
        'started_at',
        'completed_at'
    ],
    title: 'AnalysisReportPublic'
} as const;

export const AnalysisReportsPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/AnalysisReportPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'AnalysisReportsPublic'
} as const;

export const AnalysisStatusSchema = {
    type: 'string',
    enum: [
        'pending',
        'running',
        'completed',
        'failed'
    ],
    title: 'AnalysisStatus'
} as const;

export const ApiKeyCreateInSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: [
        'name'
    ],
    title: 'ApiKeyCreateIn'
} as const;

export const ApiKeyCreatedOutSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        repository_id: {
            type: 'string',
            format: 'uuid',
            title: 'Repository Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        plaintext_key: {
            type: 'string',
            title: 'Plaintext Key'
        }
    },
    type: 'object',
    required: [
        'id',
        'repository_id',
        'name',
        'plaintext_key'
    ],
    title: 'ApiKeyCreatedOut'
} as const;

export const AuditLogPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Id'
        },
        action: {
            type: 'string',
            title: 'Action'
        },
        resource_type: {
            type: 'string',
            title: 'Resource Type'
        },
        resource_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resource Id'
        },
        details: {
            additionalProperties: true,
            type: 'object',
            title: 'Details'
        },
        ip_address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ip Address'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'id',
        'user_id',
        'action',
        'resource_type',
        'resource_id',
        'details',
        'ip_address',
        'created_at'
    ],
    title: 'AuditLogPublic'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: [
        'username',
        'password'
    ],
    title: 'Body_login-login_access_token'
} as const;

export const CloudAnalysisReportPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        repository_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Repository Id'
        },
        cloud_connection_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cloud Connection Id'
        },
        analysis_type: {
            type: 'string',
            title: 'Analysis Type'
        },
        platform: {
            type: 'string',
            title: 'Platform'
        },
        trigger_type: {
            type: 'string',
            title: 'Trigger Type'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        total_violations: {
            type: 'integer',
            title: 'Total Violations'
        },
        violations_by_severity: {
            additionalProperties: true,
            type: 'object',
            title: 'Violations By Severity'
        },
        violations_by_platform: {
            additionalProperties: true,
            type: 'object',
            title: 'Violations By Platform'
        },
        score: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Score'
        },
        grade: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grade'
        },
        error_message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Message'
        },
        started_at: {
            type: 'string',
            format: 'date-time',
            title: 'Started At'
        },
        completed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Completed At'
        }
    },
    type: 'object',
    required: [
        'id',
        'repository_id',
        'cloud_connection_id',
        'analysis_type',
        'platform',
        'trigger_type',
        'status',
        'total_violations',
        'violations_by_severity',
        'violations_by_platform',
        'score',
        'grade',
        'error_message',
        'started_at',
        'completed_at'
    ],
    title: 'CloudAnalysisReportPublic'
} as const;

export const CloudAnalysisReportsPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/CloudAnalysisReportPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'CloudAnalysisReportsPublic'
} as const;

export const CloudConnectionCreateSchema = {
    properties: {
        platform: {
            type: 'string',
            title: 'Platform'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        credentials: {
            additionalProperties: true,
            type: 'object',
            title: 'Credentials'
        }
    },
    type: 'object',
    required: [
        'platform',
        'name',
        'credentials'
    ],
    title: 'CloudConnectionCreate'
} as const;

export const CloudConnectionPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        platform: {
            type: 'string',
            title: 'Platform'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        account_metadata: {
            additionalProperties: true,
            type: 'object',
            title: 'Account Metadata'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'id',
        'platform',
        'name',
        'account_metadata',
        'enabled',
        'created_at'
    ],
    title: 'CloudConnectionPublic'
} as const;

export const CloudConnectionsPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/CloudConnectionPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'CloudConnectionsPublic'
} as const;

export const CloudRulesPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/RegoRulePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'CloudRulesPublic'
} as const;

export const CloudViolationPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        report_id: {
            type: 'string',
            format: 'uuid',
            title: 'Report Id'
        },
        rule_id: {
            type: 'string',
            title: 'Rule Id'
        },
        platform: {
            type: 'string',
            title: 'Platform'
        },
        severity: {
            type: 'string',
            title: 'Severity'
        },
        category: {
            type: 'string',
            title: 'Category'
        },
        analysis_type: {
            type: 'string',
            title: 'Analysis Type'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        resource_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resource Type'
        },
        resource_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resource Name'
        },
        resource_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resource Path'
        },
        fix_hint: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fix Hint'
        },
        is_resolved: {
            type: 'boolean',
            title: 'Is Resolved'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'id',
        'report_id',
        'rule_id',
        'platform',
        'severity',
        'category',
        'analysis_type',
        'message',
        'resource_type',
        'resource_name',
        'resource_path',
        'fix_hint',
        'is_resolved',
        'created_at'
    ],
    title: 'CloudViolationPublic'
} as const;

export const CloudViolationsPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/CloudViolationPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'CloudViolationsPublic'
} as const;

export const EnergyScorePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        repository_id: {
            type: 'string',
            format: 'uuid',
            title: 'Repository Id'
        },
        report_id: {
            type: 'string',
            format: 'uuid',
            title: 'Report Id'
        },
        energy_kwh: {
            type: 'number',
            title: 'Energy Kwh'
        },
        carbon_grams: {
            type: 'number',
            title: 'Carbon Grams'
        },
        grid_intensity_gco2_kwh: {
            type: 'number',
            title: 'Grid Intensity Gco2 Kwh'
        },
        runner_region: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Runner Region'
        },
        score_breakdown: {
            additionalProperties: true,
            type: 'object',
            title: 'Score Breakdown'
        },
        overall_score: {
            type: 'number',
            title: 'Overall Score'
        },
        grade: {
            type: 'string',
            title: 'Grade'
        },
        calculated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Calculated At'
        }
    },
    type: 'object',
    required: [
        'id',
        'repository_id',
        'report_id',
        'energy_kwh',
        'carbon_grams',
        'grid_intensity_gco2_kwh',
        'runner_region',
        'score_breakdown',
        'overall_score',
        'grade',
        'calculated_at'
    ],
    title: 'EnergyScorePublic'
} as const;

export const GitProviderSchema = {
    type: 'string',
    enum: [
        'github',
        'gitlab',
        'bitbucket'
    ],
    title: 'GitProvider'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                $ref: '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MemberAddInSchema = {
    properties: {
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        role: {
            type: 'string',
            title: 'Role',
            default: 'member'
        }
    },
    type: 'object',
    required: [
        'user_id'
    ],
    title: 'MemberAddIn'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: [
        'message'
    ],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: [
        'token',
        'new_password'
    ],
    title: 'NewPassword'
} as const;

export const OAuthCodeExchangeSchema = {
    properties: {
        code: {
            type: 'string',
            title: 'Code'
        },
        redirect_uri: {
            type: 'string',
            title: 'Redirect Uri'
        }
    },
    type: 'object',
    required: [
        'code',
        'redirect_uri'
    ],
    title: 'OAuthCodeExchange',
    description: 'Body for both /exchange and /link — the authorization code + the exact\nredirect_uri used when opening the provider consent screen (required by\nmost providers to validate the code exchange).'
} as const;

export const OAuthConnectionPublicSchema = {
    properties: {
        provider: {
            $ref: '#/components/schemas/GitProvider',
            maxLength: 50
        },
        provider_user_id: {
            type: 'string',
            maxLength: 255,
            title: 'Provider User Id'
        },
        provider_username: {
            type: 'string',
            maxLength: 255,
            title: 'Provider Username'
        },
        provider_email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Provider Email'
        },
        scopes: {
            type: 'string',
            maxLength: 500,
            title: 'Scopes',
            default: ''
        },
        connection_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Connection Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        instance_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Instance Url'
        },
        token_expires_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Token Expires At'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: [
        'provider',
        'provider_user_id',
        'provider_username',
        'id',
        'user_id',
        'instance_url',
        'token_expires_at',
        'created_at',
        'updated_at'
    ],
    title: 'OAuthConnectionPublic'
} as const;

export const OAuthConnectionsPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/OAuthConnectionPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'OAuthConnectionsPublic'
} as const;

export const OAuthExchangeResponseSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        }
    },
    type: 'object',
    required: [
        'access_token'
    ],
    title: 'OAuthExchangeResponse'
} as const;

export const OAuthLinkResponseSchema = {
    properties: {
        provider_username: {
            type: 'string',
            title: 'Provider Username'
        }
    },
    type: 'object',
    required: [
        'provider_username'
    ],
    title: 'OAuthLinkResponse'
} as const;

export const OSSFixRequestInSchema = {
    properties: {
        repository_id: {
            type: 'string',
            format: 'uuid',
            title: 'Repository Id'
        },
        violation_id: {
            type: 'string',
            format: 'uuid',
            title: 'Violation Id'
        }
    },
    type: 'object',
    required: [
        'repository_id',
        'violation_id'
    ],
    title: 'OSSFixRequestIn'
} as const;

export const OSSFixRequestPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        repository_id: {
            type: 'string',
            format: 'uuid',
            title: 'Repository Id'
        },
        violation_id: {
            type: 'string',
            format: 'uuid',
            title: 'Violation Id'
        },
        requester_user_id: {
            type: 'string',
            format: 'uuid',
            title: 'Requester User Id'
        },
        status: {
            $ref: '#/components/schemas/OSSRequestStatus'
        },
        queued_at: {
            type: 'string',
            format: 'date-time',
            title: 'Queued At'
        },
        processed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Processed At'
        },
        pr_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pr Url'
        },
        position_in_queue: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Position In Queue'
        }
    },
    type: 'object',
    required: [
        'id',
        'repository_id',
        'violation_id',
        'requester_user_id',
        'status',
        'queued_at',
        'processed_at',
        'pr_url',
        'position_in_queue'
    ],
    title: 'OSSFixRequestPublic'
} as const;

export const OSSRequestStatusSchema = {
    type: 'string',
    enum: [
        'queued',
        'processing',
        'completed',
        'expired'
    ],
    title: 'OSSRequestStatus'
} as const;

export const OrgCreateInSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        }
    },
    type: 'object',
    required: [
        'name',
        'slug'
    ],
    title: 'OrgCreateIn'
} as const;

export const OrganizationMemberPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        organization_id: {
            type: 'string',
            format: 'uuid',
            title: 'Organization Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        role: {
            type: 'string',
            title: 'Role'
        },
        joined_at: {
            type: 'string',
            format: 'date-time',
            title: 'Joined At'
        }
    },
    type: 'object',
    required: [
        'id',
        'organization_id',
        'user_id',
        'role',
        'joined_at'
    ],
    title: 'OrganizationMemberPublic'
} as const;

export const OrganizationPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        },
        created_by_user_id: {
            type: 'string',
            format: 'uuid',
            title: 'Created By User Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'id',
        'name',
        'slug',
        'created_by_user_id',
        'created_at'
    ],
    title: 'OrganizationPublic'
} as const;

export const PRSourceSchema = {
    type: 'string',
    enum: [
        'cold_outreach',
        'installed',
        'oss_queue'
    ],
    title: 'PRSource'
} as const;

export const PRStatusSchema = {
    type: 'string',
    enum: [
        'open',
        'merged',
        'closed'
    ],
    title: 'PRStatus'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: [
        'email',
        'password',
        'full_name'
    ],
    title: 'PrivateUserCreate'
} as const;

export const RegoRulePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        rule_id: {
            type: 'string',
            title: 'Rule Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        category: {
            type: 'string',
            title: 'Category'
        },
        severity: {
            $ref: '#/components/schemas/ViolationSeverity'
        },
        provider: {
            type: 'string',
            title: 'Provider'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled'
        },
        rule_type: {
            type: 'string',
            title: 'Rule Type'
        }
    },
    type: 'object',
    required: [
        'id',
        'rule_id',
        'name',
        'description',
        'category',
        'severity',
        'provider',
        'enabled',
        'rule_type'
    ],
    title: 'RegoRulePublic'
} as const;

export const RepoModeSchema = {
    type: 'string',
    enum: [
        'cold_outreach',
        'installed'
    ],
    title: 'RepoMode'
} as const;

export const RepositoriesPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/RepositoryWithScore'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'RepositoriesPublic'
} as const;

export const RepositoryApiKeyPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        repository_id: {
            type: 'string',
            format: 'uuid',
            title: 'Repository Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        last_used_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Used At'
        }
    },
    type: 'object',
    required: [
        'id',
        'repository_id',
        'name',
        'is_active',
        'created_at',
        'last_used_at'
    ],
    title: 'RepositoryApiKeyPublic'
} as const;

export const RepositoryPublicSchema = {
    properties: {
        github_repo_id: {
            type: 'integer',
            title: 'Github Repo Id'
        },
        full_name: {
            type: 'string',
            maxLength: 500,
            title: 'Full Name'
        },
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        owner_login: {
            type: 'string',
            maxLength: 255,
            title: 'Owner Login'
        },
        private: {
            type: 'boolean',
            title: 'Private',
            default: false
        },
        default_branch: {
            type: 'string',
            maxLength: 255,
            title: 'Default Branch',
            default: 'main'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        oauth_connection_id: {
            type: 'string',
            format: 'uuid',
            title: 'Oauth Connection Id'
        },
        github_webhook_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Github Webhook Id'
        },
        provider: {
            $ref: '#/components/schemas/GitProvider'
        },
        provider_repo_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Provider Repo Id'
        },
        webhook_active: {
            type: 'boolean',
            title: 'Webhook Active'
        },
        mode: {
            $ref: '#/components/schemas/RepoMode'
        },
        poll_frequency_hours: {
            type: 'integer',
            title: 'Poll Frequency Hours'
        },
        pass_grade: {
            type: 'string',
            title: 'Pass Grade'
        },
        pr_comments_enabled: {
            type: 'boolean',
            title: 'Pr Comments Enabled'
        },
        status_checks_enabled: {
            type: 'boolean',
            title: 'Status Checks Enabled'
        },
        auto_pr_enabled: {
            type: 'boolean',
            title: 'Auto Pr Enabled'
        },
        auto_pr_rules_excluded: {
            items: {},
            type: 'array',
            title: 'Auto Pr Rules Excluded'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: [
        'github_repo_id',
        'full_name',
        'name',
        'owner_login',
        'id',
        'oauth_connection_id',
        'github_webhook_id',
        'provider',
        'provider_repo_id',
        'webhook_active',
        'mode',
        'poll_frequency_hours',
        'pass_grade',
        'pr_comments_enabled',
        'status_checks_enabled',
        'auto_pr_enabled',
        'auto_pr_rules_excluded',
        'created_at',
        'updated_at'
    ],
    title: 'RepositoryPublic'
} as const;

export const RepositoryRuleOverridePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        repository_id: {
            type: 'string',
            format: 'uuid',
            title: 'Repository Id'
        },
        rule_id: {
            type: 'string',
            title: 'Rule Id'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled'
        }
    },
    type: 'object',
    required: [
        'id',
        'repository_id',
        'rule_id',
        'enabled'
    ],
    title: 'RepositoryRuleOverridePublic'
} as const;

export const RepositorySettingsSchema = {
    properties: {
        pass_grade: {
            type: 'string',
            maxLength: 1,
            title: 'Pass Grade',
            default: 'C'
        },
        pr_comments_enabled: {
            type: 'boolean',
            title: 'Pr Comments Enabled',
            default: true
        },
        status_checks_enabled: {
            type: 'boolean',
            title: 'Status Checks Enabled',
            default: true
        },
        auto_pr_enabled: {
            type: 'boolean',
            title: 'Auto Pr Enabled',
            default: true
        },
        auto_pr_rules_excluded: {
            items: {},
            type: 'array',
            title: 'Auto Pr Rules Excluded'
        }
    },
    type: 'object',
    title: 'RepositorySettings',
    description: 'User-configurable per-repository settings.'
} as const;

export const RepositoryUpdateSchema = {
    properties: {
        default_branch: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Default Branch'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        webhook_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Webhook Active'
        }
    },
    type: 'object',
    title: 'RepositoryUpdate'
} as const;

export const RepositoryWithScoreSchema = {
    properties: {
        github_repo_id: {
            type: 'integer',
            title: 'Github Repo Id'
        },
        full_name: {
            type: 'string',
            maxLength: 500,
            title: 'Full Name'
        },
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        owner_login: {
            type: 'string',
            maxLength: 255,
            title: 'Owner Login'
        },
        private: {
            type: 'boolean',
            title: 'Private',
            default: false
        },
        default_branch: {
            type: 'string',
            maxLength: 255,
            title: 'Default Branch',
            default: 'main'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        oauth_connection_id: {
            type: 'string',
            format: 'uuid',
            title: 'Oauth Connection Id'
        },
        github_webhook_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Github Webhook Id'
        },
        provider: {
            $ref: '#/components/schemas/GitProvider'
        },
        provider_repo_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Provider Repo Id'
        },
        webhook_active: {
            type: 'boolean',
            title: 'Webhook Active'
        },
        mode: {
            $ref: '#/components/schemas/RepoMode'
        },
        poll_frequency_hours: {
            type: 'integer',
            title: 'Poll Frequency Hours'
        },
        pass_grade: {
            type: 'string',
            title: 'Pass Grade'
        },
        pr_comments_enabled: {
            type: 'boolean',
            title: 'Pr Comments Enabled'
        },
        status_checks_enabled: {
            type: 'boolean',
            title: 'Status Checks Enabled'
        },
        auto_pr_enabled: {
            type: 'boolean',
            title: 'Auto Pr Enabled'
        },
        auto_pr_rules_excluded: {
            items: {},
            type: 'array',
            title: 'Auto Pr Rules Excluded'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        latest_grade: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Latest Grade'
        },
        latest_score: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Latest Score'
        },
        last_analyzed_at: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Analyzed At'
        }
    },
    type: 'object',
    required: [
        'github_repo_id',
        'full_name',
        'name',
        'owner_login',
        'id',
        'oauth_connection_id',
        'github_webhook_id',
        'provider',
        'provider_repo_id',
        'webhook_active',
        'mode',
        'poll_frequency_hours',
        'pass_grade',
        'pr_comments_enabled',
        'status_checks_enabled',
        'auto_pr_enabled',
        'auto_pr_rules_excluded',
        'created_at',
        'updated_at'
    ],
    title: 'RepositoryWithScore',
    description: 'RepositoryPublic extended with the latest energy score summary.'
} as const;

export const RuleOverrideInSchema = {
    properties: {
        rule_id: {
            type: 'string',
            title: 'Rule Id'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled'
        }
    },
    type: 'object',
    required: [
        'rule_id',
        'enabled'
    ],
    title: 'RuleOverrideIn'
} as const;

export const ScoreHistoryPublicSchema = {
    properties: {
        date: {
            type: 'string',
            title: 'Date'
        },
        grade: {
            type: 'string',
            title: 'Grade'
        },
        overall_score: {
            type: 'number',
            title: 'Overall Score'
        },
        energy_kwh_total: {
            type: 'number',
            title: 'Energy Kwh Total'
        },
        carbon_grams_total: {
            type: 'number',
            title: 'Carbon Grams Total'
        }
    },
    type: 'object',
    required: [
        'date',
        'grade',
        'overall_score',
        'energy_kwh_total',
        'carbon_grams_total'
    ],
    title: 'ScoreHistoryPublic'
} as const;

export const TelemetryDataPointPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        repository_id: {
            type: 'string',
            format: 'uuid',
            title: 'Repository Id'
        },
        workflow_run_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Workflow Run Id'
        },
        job_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Job Name'
        },
        step_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Step Name'
        },
        duration_seconds: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duration Seconds'
        },
        runner_os: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Runner Os'
        },
        runner_arch: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Runner Arch'
        },
        cpu_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cpu Count'
        },
        memory_mb: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Memory Mb'
        },
        cache_hit: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cache Hit'
        },
        collected_at: {
            type: 'string',
            format: 'date-time',
            title: 'Collected At'
        }
    },
    type: 'object',
    required: [
        'id',
        'repository_id',
        'workflow_run_id',
        'job_name',
        'step_name',
        'duration_seconds',
        'runner_os',
        'runner_arch',
        'cpu_count',
        'memory_mb',
        'cache_hit',
        'collected_at'
    ],
    title: 'TelemetryDataPointPublic'
} as const;

export const TelemetryPayloadSchema = {
    properties: {
        workflow_run_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Workflow Run Id'
        },
        job_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Job Name'
        },
        step_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Step Name'
        },
        duration_seconds: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duration Seconds'
        },
        runner_os: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Runner Os'
        },
        runner_arch: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Runner Arch'
        },
        cpu_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cpu Count'
        },
        memory_mb: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Memory Mb'
        },
        cache_hit: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cache Hit'
        },
        network_bytes_in: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Network Bytes In'
        },
        network_bytes_out: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Network Bytes Out'
        },
        raw_data: {
            additionalProperties: true,
            type: 'object',
            title: 'Raw Data',
            default: {}
        }
    },
    type: 'object',
    title: 'TelemetryPayload'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: [
        'access_token'
    ],
    title: 'Token'
} as const;

export const TriggerDynamicResponseSchema = {
    properties: {
        report_id: {
            type: 'string',
            title: 'Report Id'
        },
        task_id: {
            type: 'string',
            title: 'Task Id'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: [
        'report_id',
        'task_id',
        'message'
    ],
    title: 'TriggerDynamicResponse'
} as const;

export const TriggerStaticResponseSchema = {
    properties: {
        report_id: {
            type: 'string',
            title: 'Report Id'
        },
        task_id: {
            type: 'string',
            title: 'Task Id'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: [
        'report_id',
        'task_id',
        'message'
    ],
    title: 'TriggerStaticResponse'
} as const;

export const TriggerTypeSchema = {
    type: 'string',
    enum: [
        'webhook',
        'manual',
        'periodic'
    ],
    title: 'TriggerType'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: [
        'current_password',
        'new_password'
    ],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: [
        'email',
        'password'
    ],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'email',
        'id'
    ],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: [
        'email',
        'password'
    ],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: [
        'loc',
        'msg',
        'type'
    ],
    title: 'ValidationError'
} as const;

export const VerdexPullRequestPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        repository_id: {
            type: 'string',
            format: 'uuid',
            title: 'Repository Id'
        },
        report_id: {
            type: 'string',
            format: 'uuid',
            title: 'Report Id'
        },
        provider_pr_number: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Provider Pr Number'
        },
        provider_pr_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Provider Pr Url'
        },
        branch_name: {
            type: 'string',
            title: 'Branch Name'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        status: {
            $ref: '#/components/schemas/PRStatus'
        },
        source: {
            $ref: '#/components/schemas/PRSource'
        },
        fork_full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fork Full Name'
        },
        fix_ids: {
            items: {},
            type: 'array',
            title: 'Fix Ids'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        closed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Closed At'
        }
    },
    type: 'object',
    required: [
        'id',
        'repository_id',
        'report_id',
        'provider_pr_number',
        'provider_pr_url',
        'branch_name',
        'title',
        'status',
        'source',
        'fork_full_name',
        'fix_ids',
        'created_at',
        'closed_at'
    ],
    title: 'VerdexPullRequestPublic'
} as const;

export const ViolationPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        report_id: {
            type: 'string',
            format: 'uuid',
            title: 'Report Id'
        },
        rule_id: {
            type: 'string',
            title: 'Rule Id'
        },
        severity: {
            $ref: '#/components/schemas/ViolationSeverity'
        },
        category: {
            type: 'string',
            title: 'Category'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        job_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Job Name'
        },
        workflow_file: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Workflow File'
        },
        fix_hint: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fix Hint'
        },
        is_resolved: {
            type: 'boolean',
            title: 'Is Resolved'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'id',
        'report_id',
        'rule_id',
        'severity',
        'category',
        'message',
        'job_name',
        'workflow_file',
        'fix_hint',
        'is_resolved',
        'created_at'
    ],
    title: 'ViolationPublic'
} as const;

export const ViolationSeveritySchema = {
    type: 'string',
    enum: [
        'info',
        'warning',
        'error'
    ],
    title: 'ViolationSeverity'
} as const;

export const ViolationsPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/ViolationPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'ViolationsPublic'
} as const;
