// This file is auto-generated by @hey-api/openapi-ts

/**
 * AIFixSuggestionPublic
 */
export type AiFixSuggestionPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Violation Id
     */
    violation_id: string;
    provider: AiProviderName;
    /**
     * Model
     */
    model: string;
    /**
     * Suggestion
     */
    suggestion: string;
    /**
     * Prompt Tokens
     */
    prompt_tokens: number;
    /**
     * Completion Tokens
     */
    completion_tokens: number;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * AIProviderName
 */
export type AiProviderName = 'openai' | 'anthropic' | 'google' | 'ollama';

/**
 * AnalysisReportPublic
 */
export type AnalysisReportPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Repository Id
     */
    repository_id: string;
    trigger_type: TriggerType;
    /**
     * Trigger Ref
     */
    trigger_ref: string | null;
    status: AnalysisStatus;
    /**
     * Total Violations
     */
    total_violations: number;
    /**
     * Violations By Severity
     */
    violations_by_severity: {
        [key: string]: unknown;
    };
    /**
     * Score
     */
    score: number | null;
    /**
     * Grade
     */
    grade: string | null;
    /**
     * Error Message
     */
    error_message: string | null;
    /**
     * Started At
     */
    started_at: string;
    /**
     * Completed At
     */
    completed_at: string | null;
};

/**
 * AnalysisReportsPublic
 */
export type AnalysisReportsPublic = {
    /**
     * Data
     */
    data: Array<AnalysisReportPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * AnalysisStatus
 */
export type AnalysisStatus = 'pending' | 'running' | 'completed' | 'failed';

/**
 * ApiKeyCreateIn
 */
export type ApiKeyCreateIn = {
    /**
     * Name
     */
    name: string;
};

/**
 * ApiKeyCreatedOut
 */
export type ApiKeyCreatedOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Repository Id
     */
    repository_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Plaintext Key
     */
    plaintext_key: string;
};

/**
 * AuditLogPublic
 */
export type AuditLogPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string | null;
    /**
     * Action
     */
    action: string;
    /**
     * Resource Type
     */
    resource_type: string;
    /**
     * Resource Id
     */
    resource_id: string | null;
    /**
     * Details
     */
    details: {
        [key: string]: unknown;
    };
    /**
     * Ip Address
     */
    ip_address: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * Body_login-login_access_token
 */
export type BodyLoginLoginAccessToken = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * CloudAnalysisReportPublic
 */
export type CloudAnalysisReportPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Repository Id
     */
    repository_id: string | null;
    /**
     * Cloud Connection Id
     */
    cloud_connection_id: string | null;
    /**
     * Analysis Type
     */
    analysis_type: string;
    /**
     * Platform
     */
    platform: string;
    /**
     * Trigger Type
     */
    trigger_type: string;
    /**
     * Status
     */
    status: string;
    /**
     * Total Violations
     */
    total_violations: number;
    /**
     * Violations By Severity
     */
    violations_by_severity: {
        [key: string]: unknown;
    };
    /**
     * Violations By Platform
     */
    violations_by_platform: {
        [key: string]: unknown;
    };
    /**
     * Score
     */
    score: number | null;
    /**
     * Grade
     */
    grade: string | null;
    /**
     * Error Message
     */
    error_message: string | null;
    /**
     * Started At
     */
    started_at: string;
    /**
     * Completed At
     */
    completed_at: string | null;
};

/**
 * CloudAnalysisReportsPublic
 */
export type CloudAnalysisReportsPublic = {
    /**
     * Data
     */
    data: Array<CloudAnalysisReportPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * CloudConnectionCreate
 */
export type CloudConnectionCreate = {
    /**
     * Platform
     */
    platform: string;
    /**
     * Name
     */
    name: string;
    /**
     * Credentials
     */
    credentials: {
        [key: string]: unknown;
    };
};

/**
 * CloudConnectionPublic
 */
export type CloudConnectionPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Platform
     */
    platform: string;
    /**
     * Name
     */
    name: string;
    /**
     * Account Metadata
     */
    account_metadata: {
        [key: string]: unknown;
    };
    /**
     * Enabled
     */
    enabled: boolean;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * CloudConnectionsPublic
 */
export type CloudConnectionsPublic = {
    /**
     * Data
     */
    data: Array<CloudConnectionPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * CloudRulesPublic
 */
export type CloudRulesPublic = {
    /**
     * Data
     */
    data: Array<RegoRulePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * CloudViolationPublic
 */
export type CloudViolationPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Report Id
     */
    report_id: string;
    /**
     * Rule Id
     */
    rule_id: string;
    /**
     * Platform
     */
    platform: string;
    /**
     * Severity
     */
    severity: string;
    /**
     * Category
     */
    category: string;
    /**
     * Analysis Type
     */
    analysis_type: string;
    /**
     * Message
     */
    message: string;
    /**
     * Resource Type
     */
    resource_type: string | null;
    /**
     * Resource Name
     */
    resource_name: string | null;
    /**
     * Resource Path
     */
    resource_path: string | null;
    /**
     * Fix Hint
     */
    fix_hint: string | null;
    /**
     * Is Resolved
     */
    is_resolved: boolean;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * CloudViolationsPublic
 */
export type CloudViolationsPublic = {
    /**
     * Data
     */
    data: Array<CloudViolationPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * EnergyScorePublic
 */
export type EnergyScorePublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Repository Id
     */
    repository_id: string;
    /**
     * Report Id
     */
    report_id: string;
    /**
     * Energy Kwh
     */
    energy_kwh: number;
    /**
     * Carbon Grams
     */
    carbon_grams: number;
    /**
     * Grid Intensity Gco2 Kwh
     */
    grid_intensity_gco2_kwh: number;
    /**
     * Runner Region
     */
    runner_region: string | null;
    /**
     * Score Breakdown
     */
    score_breakdown: {
        [key: string]: unknown;
    };
    /**
     * Overall Score
     */
    overall_score: number;
    /**
     * Grade
     */
    grade: string;
    /**
     * Calculated At
     */
    calculated_at: string;
};

/**
 * GitProvider
 */
export type GitProvider = 'github' | 'gitlab' | 'bitbucket';

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MemberAddIn
 */
export type MemberAddIn = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Role
     */
    role?: string;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * OAuthConnectionPublic
 */
export type OAuthConnectionPublic = {
    provider: GitProvider;
    /**
     * Provider User Id
     */
    provider_user_id: string;
    /**
     * Provider Username
     */
    provider_username: string;
    /**
     * Provider Email
     */
    provider_email?: string | null;
    /**
     * Scopes
     */
    scopes?: string;
    /**
     * Connection Name
     */
    connection_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Instance Url
     */
    instance_url: string | null;
    /**
     * Token Expires At
     */
    token_expires_at: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * OAuthConnectionsPublic
 */
export type OAuthConnectionsPublic = {
    /**
     * Data
     */
    data: Array<OAuthConnectionPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * OSSFixRequestIn
 */
export type OssFixRequestIn = {
    /**
     * Repository Id
     */
    repository_id: string;
    /**
     * Violation Id
     */
    violation_id: string;
};

/**
 * OSSFixRequestPublic
 */
export type OssFixRequestPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Repository Id
     */
    repository_id: string;
    /**
     * Violation Id
     */
    violation_id: string;
    /**
     * Requester User Id
     */
    requester_user_id: string;
    status: OssRequestStatus;
    /**
     * Queued At
     */
    queued_at: string;
    /**
     * Processed At
     */
    processed_at: string | null;
    /**
     * Pr Url
     */
    pr_url: string | null;
    /**
     * Position In Queue
     */
    position_in_queue: number | null;
};

/**
 * OSSRequestStatus
 */
export type OssRequestStatus = 'queued' | 'processing' | 'completed' | 'expired';

/**
 * OrgCreateIn
 */
export type OrgCreateIn = {
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
};

/**
 * OrganizationMemberPublic
 */
export type OrganizationMemberPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Organization Id
     */
    organization_id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Role
     */
    role: string;
    /**
     * Joined At
     */
    joined_at: string;
};

/**
 * OrganizationPublic
 */
export type OrganizationPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Created By User Id
     */
    created_by_user_id: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * PRSource
 */
export type PrSource = 'cold_outreach' | 'installed' | 'oss_queue';

/**
 * PRStatus
 */
export type PrStatus = 'open' | 'merged' | 'closed';

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * RegoRulePublic
 */
export type RegoRulePublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Rule Id
     */
    rule_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    /**
     * Category
     */
    category: string;
    severity: ViolationSeverity;
    /**
     * Provider
     */
    provider: string;
    /**
     * Enabled
     */
    enabled: boolean;
    /**
     * Rule Type
     */
    rule_type: string;
};

/**
 * RepoMode
 */
export type RepoMode = 'cold_outreach' | 'installed';

/**
 * RepositoriesPublic
 */
export type RepositoriesPublic = {
    /**
     * Data
     */
    data: Array<RepositoryWithScore>;
    /**
     * Count
     */
    count: number;
};

/**
 * RepositoryApiKeyPublic
 */
export type RepositoryApiKeyPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Repository Id
     */
    repository_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Last Used At
     */
    last_used_at: string | null;
};

/**
 * RepositoryPublic
 */
export type RepositoryPublic = {
    /**
     * Github Repo Id
     */
    github_repo_id: number;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Name
     */
    name: string;
    /**
     * Owner Login
     */
    owner_login: string;
    /**
     * Private
     */
    private?: boolean;
    /**
     * Default Branch
     */
    default_branch?: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Oauth Connection Id
     */
    oauth_connection_id: string;
    /**
     * Github Webhook Id
     */
    github_webhook_id: number | null;
    provider: GitProvider;
    /**
     * Provider Repo Id
     */
    provider_repo_id: string | null;
    /**
     * Webhook Active
     */
    webhook_active: boolean;
    mode: RepoMode;
    /**
     * Poll Frequency Hours
     */
    poll_frequency_hours: number;
    /**
     * Pass Grade
     */
    pass_grade: string;
    /**
     * Pr Comments Enabled
     */
    pr_comments_enabled: boolean;
    /**
     * Status Checks Enabled
     */
    status_checks_enabled: boolean;
    /**
     * Auto Pr Enabled
     */
    auto_pr_enabled: boolean;
    /**
     * Auto Pr Rules Excluded
     */
    auto_pr_rules_excluded: Array<unknown>;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * RepositoryRuleOverridePublic
 */
export type RepositoryRuleOverridePublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Repository Id
     */
    repository_id: string;
    /**
     * Rule Id
     */
    rule_id: string;
    /**
     * Enabled
     */
    enabled: boolean;
};

/**
 * RepositorySettings
 * User-configurable per-repository settings.
 */
export type RepositorySettings = {
    /**
     * Pass Grade
     */
    pass_grade?: string;
    /**
     * Pr Comments Enabled
     */
    pr_comments_enabled?: boolean;
    /**
     * Status Checks Enabled
     */
    status_checks_enabled?: boolean;
    /**
     * Auto Pr Enabled
     */
    auto_pr_enabled?: boolean;
    /**
     * Auto Pr Rules Excluded
     */
    auto_pr_rules_excluded?: Array<unknown>;
};

/**
 * RepositoryUpdate
 */
export type RepositoryUpdate = {
    /**
     * Default Branch
     */
    default_branch?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Webhook Active
     */
    webhook_active?: boolean | null;
};

/**
 * RepositoryWithScore
 * RepositoryPublic extended with the latest energy score summary.
 */
export type RepositoryWithScore = {
    /**
     * Github Repo Id
     */
    github_repo_id: number;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Name
     */
    name: string;
    /**
     * Owner Login
     */
    owner_login: string;
    /**
     * Private
     */
    private?: boolean;
    /**
     * Default Branch
     */
    default_branch?: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Oauth Connection Id
     */
    oauth_connection_id: string;
    /**
     * Github Webhook Id
     */
    github_webhook_id: number | null;
    provider: GitProvider;
    /**
     * Provider Repo Id
     */
    provider_repo_id: string | null;
    /**
     * Webhook Active
     */
    webhook_active: boolean;
    mode: RepoMode;
    /**
     * Poll Frequency Hours
     */
    poll_frequency_hours: number;
    /**
     * Pass Grade
     */
    pass_grade: string;
    /**
     * Pr Comments Enabled
     */
    pr_comments_enabled: boolean;
    /**
     * Status Checks Enabled
     */
    status_checks_enabled: boolean;
    /**
     * Auto Pr Enabled
     */
    auto_pr_enabled: boolean;
    /**
     * Auto Pr Rules Excluded
     */
    auto_pr_rules_excluded: Array<unknown>;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Latest Grade
     */
    latest_grade?: string | null;
    /**
     * Latest Score
     */
    latest_score?: number | null;
    /**
     * Last Analyzed At
     */
    last_analyzed_at?: string | null;
};

/**
 * RuleOverrideIn
 */
export type RuleOverrideIn = {
    /**
     * Rule Id
     */
    rule_id: string;
    /**
     * Enabled
     */
    enabled: boolean;
};

/**
 * ScoreHistoryPublic
 */
export type ScoreHistoryPublic = {
    /**
     * Date
     */
    date: string;
    /**
     * Grade
     */
    grade: string;
    /**
     * Overall Score
     */
    overall_score: number;
    /**
     * Energy Kwh Total
     */
    energy_kwh_total: number;
    /**
     * Carbon Grams Total
     */
    carbon_grams_total: number;
};

/**
 * TelemetryDataPointPublic
 */
export type TelemetryDataPointPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Repository Id
     */
    repository_id: string;
    /**
     * Workflow Run Id
     */
    workflow_run_id: number | null;
    /**
     * Job Name
     */
    job_name: string | null;
    /**
     * Step Name
     */
    step_name: string | null;
    /**
     * Duration Seconds
     */
    duration_seconds: number | null;
    /**
     * Runner Os
     */
    runner_os: string | null;
    /**
     * Runner Arch
     */
    runner_arch: string | null;
    /**
     * Cpu Count
     */
    cpu_count: number | null;
    /**
     * Memory Mb
     */
    memory_mb: number | null;
    /**
     * Cache Hit
     */
    cache_hit: boolean | null;
    /**
     * Collected At
     */
    collected_at: string;
};

/**
 * TelemetryPayload
 */
export type TelemetryPayload = {
    /**
     * Workflow Run Id
     */
    workflow_run_id?: number | null;
    /**
     * Job Name
     */
    job_name?: string | null;
    /**
     * Step Name
     */
    step_name?: string | null;
    /**
     * Duration Seconds
     */
    duration_seconds?: number | null;
    /**
     * Runner Os
     */
    runner_os?: string | null;
    /**
     * Runner Arch
     */
    runner_arch?: string | null;
    /**
     * Cpu Count
     */
    cpu_count?: number | null;
    /**
     * Memory Mb
     */
    memory_mb?: number | null;
    /**
     * Cache Hit
     */
    cache_hit?: boolean | null;
    /**
     * Network Bytes In
     */
    network_bytes_in?: number | null;
    /**
     * Network Bytes Out
     */
    network_bytes_out?: number | null;
    /**
     * Raw Data
     */
    raw_data?: {
        [key: string]: unknown;
    };
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * TriggerDynamicResponse
 */
export type TriggerDynamicResponse = {
    /**
     * Report Id
     */
    report_id: string;
    /**
     * Task Id
     */
    task_id: string;
    /**
     * Message
     */
    message: string;
};

/**
 * TriggerStaticResponse
 */
export type TriggerStaticResponse = {
    /**
     * Report Id
     */
    report_id: string;
    /**
     * Task Id
     */
    task_id: string;
    /**
     * Message
     */
    message: string;
};

/**
 * TriggerType
 */
export type TriggerType = 'webhook' | 'manual' | 'periodic';

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * VerdexPullRequestPublic
 */
export type VerdexPullRequestPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Repository Id
     */
    repository_id: string;
    /**
     * Report Id
     */
    report_id: string;
    /**
     * Provider Pr Number
     */
    provider_pr_number: number | null;
    /**
     * Provider Pr Url
     */
    provider_pr_url: string | null;
    /**
     * Branch Name
     */
    branch_name: string;
    /**
     * Title
     */
    title: string;
    status: PrStatus;
    source: PrSource;
    /**
     * Fork Full Name
     */
    fork_full_name: string | null;
    /**
     * Fix Ids
     */
    fix_ids: Array<unknown>;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Closed At
     */
    closed_at: string | null;
};

/**
 * ViolationPublic
 */
export type ViolationPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Report Id
     */
    report_id: string;
    /**
     * Rule Id
     */
    rule_id: string;
    severity: ViolationSeverity;
    /**
     * Category
     */
    category: string;
    /**
     * Message
     */
    message: string;
    /**
     * Job Name
     */
    job_name: string | null;
    /**
     * Workflow File
     */
    workflow_file: string | null;
    /**
     * Fix Hint
     */
    fix_hint: string | null;
    /**
     * Is Resolved
     */
    is_resolved: boolean;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ViolationSeverity
 */
export type ViolationSeverity = 'info' | 'warning' | 'error';

/**
 * ViolationsPublic
 */
export type ViolationsPublic = {
    /**
     * Data
     */
    data: Array<ViolationPublic>;
    /**
     * Count
     */
    count: number;
};

export type LoginLoginAccessTokenData = {
    body: BodyLoginLoginAccessToken;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type LoginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginLoginAccessTokenError = LoginLoginAccessTokenErrors[keyof LoginLoginAccessTokenErrors];

export type LoginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginLoginAccessTokenResponse = LoginLoginAccessTokenResponses[keyof LoginLoginAccessTokenResponses];

export type LoginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type LoginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type LoginTestTokenResponse = LoginTestTokenResponses[keyof LoginTestTokenResponses];

export type LoginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type LoginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginRecoverPasswordError = LoginRecoverPasswordErrors[keyof LoginRecoverPasswordErrors];

export type LoginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LoginRecoverPasswordResponse = LoginRecoverPasswordResponses[keyof LoginRecoverPasswordResponses];

export type LoginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type LoginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginResetPasswordError = LoginResetPasswordErrors[keyof LoginResetPasswordErrors];

export type LoginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LoginResetPasswordResponse = LoginResetPasswordResponses[keyof LoginResetPasswordResponses];

export type LoginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type LoginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginRecoverPasswordHtmlContentError = LoginRecoverPasswordHtmlContentErrors[keyof LoginRecoverPasswordHtmlContentErrors];

export type LoginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type LoginRecoverPasswordHtmlContentResponse = LoginRecoverPasswordHtmlContentResponses[keyof LoginRecoverPasswordHtmlContentResponses];

export type UsersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type UsersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUsersError = UsersReadUsersErrors[keyof UsersReadUsersErrors];

export type UsersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type UsersReadUsersResponse = UsersReadUsersResponses[keyof UsersReadUsersResponses];

export type UsersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type UsersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersCreateUserError = UsersCreateUserErrors[keyof UsersCreateUserErrors];

export type UsersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersCreateUserResponse = UsersCreateUserResponses[keyof UsersCreateUserResponses];

export type UsersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserMeResponse = UsersDeleteUserMeResponses[keyof UsersDeleteUserMeResponses];

export type UsersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserMeResponse = UsersReadUserMeResponses[keyof UsersReadUserMeResponses];

export type UsersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserMeError = UsersUpdateUserMeErrors[keyof UsersUpdateUserMeErrors];

export type UsersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserMeResponse = UsersUpdateUserMeResponses[keyof UsersUpdateUserMeResponses];

export type UsersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type UsersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdatePasswordMeError = UsersUpdatePasswordMeErrors[keyof UsersUpdatePasswordMeErrors];

export type UsersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersUpdatePasswordMeResponse = UsersUpdatePasswordMeResponses[keyof UsersUpdatePasswordMeResponses];

export type UsersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type UsersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersRegisterUserError = UsersRegisterUserErrors[keyof UsersRegisterUserErrors];

export type UsersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersRegisterUserResponse = UsersRegisterUserResponses[keyof UsersRegisterUserResponses];

export type UsersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersDeleteUserError = UsersDeleteUserErrors[keyof UsersDeleteUserErrors];

export type UsersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserResponse = UsersDeleteUserResponses[keyof UsersDeleteUserResponses];

export type UsersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUserByIdError = UsersReadUserByIdErrors[keyof UsersReadUserByIdErrors];

export type UsersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserByIdResponse = UsersReadUserByIdResponses[keyof UsersReadUserByIdResponses];

export type UsersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserError = UsersUpdateUserErrors[keyof UsersUpdateUserErrors];

export type UsersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserResponse = UsersUpdateUserResponses[keyof UsersUpdateUserResponses];

export type UtilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type UtilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UtilsTestEmailError = UtilsTestEmailErrors[keyof UtilsTestEmailErrors];

export type UtilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type UtilsTestEmailResponse = UtilsTestEmailResponses[keyof UtilsTestEmailResponses];

export type UtilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type UtilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     * Successful Response
     */
    200: boolean;
};

export type UtilsHealthCheckResponse = UtilsHealthCheckResponses[keyof UtilsHealthCheckResponses];

export type OauthProviderLoginData = {
    body?: never;
    path: {
        provider: GitProvider;
    };
    query?: never;
    url: '/api/v1/oauth/{provider}/login';
};

export type OauthProviderLoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OauthProviderLoginError = OauthProviderLoginErrors[keyof OauthProviderLoginErrors];

export type OauthProviderLoginResponses = {
    /**
     * Response Oauth-Provider Login
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type OauthProviderLoginResponse = OauthProviderLoginResponses[keyof OauthProviderLoginResponses];

export type OauthProviderAuthorizeData = {
    body?: never;
    path: {
        provider: GitProvider;
    };
    query?: never;
    url: '/api/v1/oauth/{provider}/authorize';
};

export type OauthProviderAuthorizeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OauthProviderAuthorizeError = OauthProviderAuthorizeErrors[keyof OauthProviderAuthorizeErrors];

export type OauthProviderAuthorizeResponses = {
    /**
     * Response Oauth-Provider Authorize
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type OauthProviderAuthorizeResponse = OauthProviderAuthorizeResponses[keyof OauthProviderAuthorizeResponses];

export type OauthProviderCallbackData = {
    body?: never;
    path: {
        provider: GitProvider;
    };
    query: {
        /**
         * Code
         */
        code: string;
        /**
         * State
         */
        state: string;
    };
    url: '/api/v1/oauth/{provider}/callback';
};

export type OauthProviderCallbackErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OauthProviderCallbackError = OauthProviderCallbackErrors[keyof OauthProviderCallbackErrors];

export type OauthProviderCallbackResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type OauthGetProviderConnectionsData = {
    body?: never;
    path: {
        provider: GitProvider;
    };
    query?: never;
    url: '/api/v1/oauth/{provider}/connection';
};

export type OauthGetProviderConnectionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OauthGetProviderConnectionsError = OauthGetProviderConnectionsErrors[keyof OauthGetProviderConnectionsErrors];

export type OauthGetProviderConnectionsResponses = {
    /**
     * Successful Response
     */
    200: OAuthConnectionsPublic;
};

export type OauthGetProviderConnectionsResponse = OauthGetProviderConnectionsResponses[keyof OauthGetProviderConnectionsResponses];

export type OauthDeleteProviderConnectionData = {
    body?: never;
    path: {
        provider: GitProvider;
        /**
         * Connection Id
         */
        connection_id: string;
    };
    query?: never;
    url: '/api/v1/oauth/{provider}/connection/{connection_id}';
};

export type OauthDeleteProviderConnectionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OauthDeleteProviderConnectionError = OauthDeleteProviderConnectionErrors[keyof OauthDeleteProviderConnectionErrors];

export type OauthDeleteProviderConnectionResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type OauthDeleteProviderConnectionResponse = OauthDeleteProviderConnectionResponses[keyof OauthDeleteProviderConnectionResponses];

export type OauthGithubInstallAppData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/oauth/github/install-app';
};

export type OauthGithubInstallAppResponses = {
    /**
     * Response Oauth-Github Install App
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type OauthGithubInstallAppResponse = OauthGithubInstallAppResponses[keyof OauthGithubInstallAppResponses];

export type RepositoriesListRepositoriesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Provider
         * Provider: github | gitlab | bitbucket
         */
        provider?: string;
    };
    url: '/api/v1/repositories/';
};

export type RepositoriesListRepositoriesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RepositoriesListRepositoriesError = RepositoriesListRepositoriesErrors[keyof RepositoriesListRepositoriesErrors];

export type RepositoriesListRepositoriesResponses = {
    /**
     * Successful Response
     */
    200: RepositoriesPublic;
};

export type RepositoriesListRepositoriesResponse = RepositoriesListRepositoriesResponses[keyof RepositoriesListRepositoriesResponses];

export type RepositoriesConnectRepositoryData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Github Repo Id
         * GitHub numeric repository ID (use for provider=github)
         */
        github_repo_id?: number;
        /**
         * Provider Repo Id
         * Provider repository ID as string (use for gitlab/bitbucket)
         */
        provider_repo_id?: string;
        /**
         * Provider
         * Provider: github | gitlab | bitbucket
         */
        provider?: string;
    };
    url: '/api/v1/repositories/';
};

export type RepositoriesConnectRepositoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RepositoriesConnectRepositoryError = RepositoriesConnectRepositoryErrors[keyof RepositoriesConnectRepositoryErrors];

export type RepositoriesConnectRepositoryResponses = {
    /**
     * Successful Response
     */
    201: RepositoryPublic;
};

export type RepositoriesConnectRepositoryResponse = RepositoriesConnectRepositoryResponses[keyof RepositoriesConnectRepositoryResponses];

export type RepositoriesListAvailableReposData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Provider
         * Provider: github | gitlab | bitbucket
         */
        provider?: string;
    };
    url: '/api/v1/repositories/available';
};

export type RepositoriesListAvailableReposErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RepositoriesListAvailableReposError = RepositoriesListAvailableReposErrors[keyof RepositoriesListAvailableReposErrors];

export type RepositoriesListAvailableReposResponses = {
    /**
     * Response Repositories-List Available Repos
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type RepositoriesListAvailableReposResponse = RepositoriesListAvailableReposResponses[keyof RepositoriesListAvailableReposResponses];

export type RepositoriesDisconnectRepositoryData = {
    body?: never;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: never;
    url: '/api/v1/repositories/{repo_id}';
};

export type RepositoriesDisconnectRepositoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RepositoriesDisconnectRepositoryError = RepositoriesDisconnectRepositoryErrors[keyof RepositoriesDisconnectRepositoryErrors];

export type RepositoriesDisconnectRepositoryResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RepositoriesDisconnectRepositoryResponse = RepositoriesDisconnectRepositoryResponses[keyof RepositoriesDisconnectRepositoryResponses];

export type RepositoriesUpdateRepositoryData = {
    body: RepositoryUpdate;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: never;
    url: '/api/v1/repositories/{repo_id}';
};

export type RepositoriesUpdateRepositoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RepositoriesUpdateRepositoryError = RepositoriesUpdateRepositoryErrors[keyof RepositoriesUpdateRepositoryErrors];

export type RepositoriesUpdateRepositoryResponses = {
    /**
     * Successful Response
     */
    200: RepositoryPublic;
};

export type RepositoriesUpdateRepositoryResponse = RepositoriesUpdateRepositoryResponses[keyof RepositoriesUpdateRepositoryResponses];

export type RepositoriesGetRepositorySettingsData = {
    body?: never;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: never;
    url: '/api/v1/repositories/{repo_id}/settings';
};

export type RepositoriesGetRepositorySettingsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RepositoriesGetRepositorySettingsError = RepositoriesGetRepositorySettingsErrors[keyof RepositoriesGetRepositorySettingsErrors];

export type RepositoriesGetRepositorySettingsResponses = {
    /**
     * Successful Response
     */
    200: RepositorySettings;
};

export type RepositoriesGetRepositorySettingsResponse = RepositoriesGetRepositorySettingsResponses[keyof RepositoriesGetRepositorySettingsResponses];

export type RepositoriesUpdateRepositorySettingsData = {
    body: RepositorySettings;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: never;
    url: '/api/v1/repositories/{repo_id}/settings';
};

export type RepositoriesUpdateRepositorySettingsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RepositoriesUpdateRepositorySettingsError = RepositoriesUpdateRepositorySettingsErrors[keyof RepositoriesUpdateRepositorySettingsErrors];

export type RepositoriesUpdateRepositorySettingsResponses = {
    /**
     * Successful Response
     */
    200: RepositorySettings;
};

export type RepositoriesUpdateRepositorySettingsResponse = RepositoriesUpdateRepositorySettingsResponses[keyof RepositoriesUpdateRepositorySettingsResponses];

export type WebhooksReceiveGithubWebhookData = {
    body?: never;
    headers: {
        /**
         * X-Github-Event
         */
        'X-GitHub-Event': string;
        /**
         * X-Hub-Signature-256
         */
        'X-Hub-Signature-256': string;
        /**
         * X-Github-Delivery
         */
        'X-GitHub-Delivery': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/webhooks/github';
};

export type WebhooksReceiveGithubWebhookErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type WebhooksReceiveGithubWebhookError = WebhooksReceiveGithubWebhookErrors[keyof WebhooksReceiveGithubWebhookErrors];

export type WebhooksReceiveGithubWebhookResponses = {
    /**
     * Response Webhooks-Receive Github Webhook
     * Successful Response
     */
    202: unknown;
};

export type WebhooksReceiveGitlabWebhookData = {
    body?: never;
    headers: {
        /**
         * X-Gitlab-Event
         */
        'X-Gitlab-Event': string;
        /**
         * X-Gitlab-Token
         */
        'X-Gitlab-Token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/webhooks/gitlab';
};

export type WebhooksReceiveGitlabWebhookErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type WebhooksReceiveGitlabWebhookError = WebhooksReceiveGitlabWebhookErrors[keyof WebhooksReceiveGitlabWebhookErrors];

export type WebhooksReceiveGitlabWebhookResponses = {
    /**
     * Response Webhooks-Receive Gitlab Webhook
     * Successful Response
     */
    202: unknown;
};

export type WebhooksReceiveBitbucketWebhookData = {
    body?: never;
    headers: {
        /**
         * X-Event-Key
         */
        'X-Event-Key': string;
        /**
         * X-Hub-Signature
         */
        'X-Hub-Signature'?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/webhooks/bitbucket';
};

export type WebhooksReceiveBitbucketWebhookErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type WebhooksReceiveBitbucketWebhookError = WebhooksReceiveBitbucketWebhookErrors[keyof WebhooksReceiveBitbucketWebhookErrors];

export type WebhooksReceiveBitbucketWebhookResponses = {
    /**
     * Response Webhooks-Receive Bitbucket Webhook
     * Successful Response
     */
    202: unknown;
};

export type DashboardGetDashboardData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/dashboard';
};

export type DashboardGetDashboardResponses = {
    /**
     * Response Dashboard-Get Dashboard
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type DashboardGetDashboardResponse = DashboardGetDashboardResponses[keyof DashboardGetDashboardResponses];

export type AnalysisTriggerAnalysisData = {
    body?: never;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: never;
    url: '/api/v1/repositories/{repo_id}/analyze';
};

export type AnalysisTriggerAnalysisErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnalysisTriggerAnalysisError = AnalysisTriggerAnalysisErrors[keyof AnalysisTriggerAnalysisErrors];

export type AnalysisTriggerAnalysisResponses = {
    /**
     * Response Analysis-Trigger Analysis
     * Successful Response
     */
    202: {
        [key: string]: unknown;
    };
};

export type AnalysisTriggerAnalysisResponse = AnalysisTriggerAnalysisResponses[keyof AnalysisTriggerAnalysisResponses];

export type AnalysisListReportsData = {
    body?: never;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/repositories/{repo_id}/reports';
};

export type AnalysisListReportsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnalysisListReportsError = AnalysisListReportsErrors[keyof AnalysisListReportsErrors];

export type AnalysisListReportsResponses = {
    /**
     * Successful Response
     */
    200: AnalysisReportsPublic;
};

export type AnalysisListReportsResponse = AnalysisListReportsResponses[keyof AnalysisListReportsResponses];

export type AnalysisGetReportData = {
    body?: never;
    path: {
        /**
         * Report Id
         */
        report_id: string;
    };
    query?: never;
    url: '/api/v1/reports/{report_id}';
};

export type AnalysisGetReportErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnalysisGetReportError = AnalysisGetReportErrors[keyof AnalysisGetReportErrors];

export type AnalysisGetReportResponses = {
    /**
     * Successful Response
     */
    200: AnalysisReportPublic;
};

export type AnalysisGetReportResponse = AnalysisGetReportResponses[keyof AnalysisGetReportResponses];

export type AnalysisListViolationsData = {
    body?: never;
    path: {
        /**
         * Report Id
         */
        report_id: string;
    };
    query?: never;
    url: '/api/v1/reports/{report_id}/violations';
};

export type AnalysisListViolationsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnalysisListViolationsError = AnalysisListViolationsErrors[keyof AnalysisListViolationsErrors];

export type AnalysisListViolationsResponses = {
    /**
     * Successful Response
     */
    200: ViolationsPublic;
};

export type AnalysisListViolationsResponse = AnalysisListViolationsResponses[keyof AnalysisListViolationsResponses];

export type AnalysisGetTaskStatusData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/v1/tasks/{task_id}';
};

export type AnalysisGetTaskStatusErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnalysisGetTaskStatusError = AnalysisGetTaskStatusErrors[keyof AnalysisGetTaskStatusErrors];

export type AnalysisGetTaskStatusResponses = {
    /**
     * Response Analysis-Get Task Status
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type AnalysisGetTaskStatusResponse = AnalysisGetTaskStatusResponses[keyof AnalysisGetTaskStatusResponses];

export type AnalysisListRulesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Enabled Only
         */
        enabled_only?: boolean;
    };
    url: '/api/v1/rules';
};

export type AnalysisListRulesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnalysisListRulesError = AnalysisListRulesErrors[keyof AnalysisListRulesErrors];

export type AnalysisListRulesResponses = {
    /**
     * Response Analysis-List Rules
     * Successful Response
     */
    200: Array<RegoRulePublic>;
};

export type AnalysisListRulesResponse = AnalysisListRulesResponses[keyof AnalysisListRulesResponses];

export type AnalysisListPullRequestsData = {
    body?: never;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/repositories/{repo_id}/pull-requests';
};

export type AnalysisListPullRequestsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnalysisListPullRequestsError = AnalysisListPullRequestsErrors[keyof AnalysisListPullRequestsErrors];

export type AnalysisListPullRequestsResponses = {
    /**
     * Response Analysis-List Pull Requests
     * Successful Response
     */
    200: Array<VerdexPullRequestPublic>;
};

export type AnalysisListPullRequestsResponse = AnalysisListPullRequestsResponses[keyof AnalysisListPullRequestsResponses];

export type AnalysisListRepoRuleOverridesData = {
    body?: never;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: never;
    url: '/api/v1/repositories/{repo_id}/rules';
};

export type AnalysisListRepoRuleOverridesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnalysisListRepoRuleOverridesError = AnalysisListRepoRuleOverridesErrors[keyof AnalysisListRepoRuleOverridesErrors];

export type AnalysisListRepoRuleOverridesResponses = {
    /**
     * Response Analysis-List Repo Rule Overrides
     * Successful Response
     */
    200: Array<RepositoryRuleOverridePublic>;
};

export type AnalysisListRepoRuleOverridesResponse = AnalysisListRepoRuleOverridesResponses[keyof AnalysisListRepoRuleOverridesResponses];

export type AnalysisUpdateRepoRuleOverridesData = {
    /**
     * Overrides In
     */
    body: Array<RuleOverrideIn>;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: never;
    url: '/api/v1/repositories/{repo_id}/rules';
};

export type AnalysisUpdateRepoRuleOverridesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnalysisUpdateRepoRuleOverridesError = AnalysisUpdateRepoRuleOverridesErrors[keyof AnalysisUpdateRepoRuleOverridesErrors];

export type AnalysisUpdateRepoRuleOverridesResponses = {
    /**
     * Response Analysis-Update Repo Rule Overrides
     * Successful Response
     */
    200: Array<RepositoryRuleOverridePublic>;
};

export type AnalysisUpdateRepoRuleOverridesResponse = AnalysisUpdateRepoRuleOverridesResponses[keyof AnalysisUpdateRepoRuleOverridesResponses];

export type CloudListCloudConnectionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/cloud/connections';
};

export type CloudListCloudConnectionsResponses = {
    /**
     * Successful Response
     */
    200: CloudConnectionsPublic;
};

export type CloudListCloudConnectionsResponse = CloudListCloudConnectionsResponses[keyof CloudListCloudConnectionsResponses];

export type CloudCreateCloudConnectionData = {
    body: CloudConnectionCreate;
    path?: never;
    query?: never;
    url: '/api/v1/cloud/connections';
};

export type CloudCreateCloudConnectionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CloudCreateCloudConnectionError = CloudCreateCloudConnectionErrors[keyof CloudCreateCloudConnectionErrors];

export type CloudCreateCloudConnectionResponses = {
    /**
     * Successful Response
     */
    201: CloudConnectionPublic;
};

export type CloudCreateCloudConnectionResponse = CloudCreateCloudConnectionResponses[keyof CloudCreateCloudConnectionResponses];

export type CloudDeleteCloudConnectionData = {
    body?: never;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
    };
    query?: never;
    url: '/api/v1/cloud/connections/{connection_id}';
};

export type CloudDeleteCloudConnectionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CloudDeleteCloudConnectionError = CloudDeleteCloudConnectionErrors[keyof CloudDeleteCloudConnectionErrors];

export type CloudDeleteCloudConnectionResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type CloudDeleteCloudConnectionResponse = CloudDeleteCloudConnectionResponses[keyof CloudDeleteCloudConnectionResponses];

export type CloudTriggerStaticAnalysisData = {
    body?: never;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: never;
    url: '/api/v1/cloud/repositories/{repo_id}/analyze/static';
};

export type CloudTriggerStaticAnalysisErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CloudTriggerStaticAnalysisError = CloudTriggerStaticAnalysisErrors[keyof CloudTriggerStaticAnalysisErrors];

export type CloudTriggerStaticAnalysisResponses = {
    /**
     * Successful Response
     */
    202: TriggerStaticResponse;
};

export type CloudTriggerStaticAnalysisResponse = CloudTriggerStaticAnalysisResponses[keyof CloudTriggerStaticAnalysisResponses];

export type CloudTriggerDynamicAnalysisData = {
    body?: never;
    path: {
        /**
         * Connection Id
         */
        connection_id: string;
    };
    query?: never;
    url: '/api/v1/cloud/connections/{connection_id}/analyze/dynamic';
};

export type CloudTriggerDynamicAnalysisErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CloudTriggerDynamicAnalysisError = CloudTriggerDynamicAnalysisErrors[keyof CloudTriggerDynamicAnalysisErrors];

export type CloudTriggerDynamicAnalysisResponses = {
    /**
     * Successful Response
     */
    202: TriggerDynamicResponse;
};

export type CloudTriggerDynamicAnalysisResponse = CloudTriggerDynamicAnalysisResponses[keyof CloudTriggerDynamicAnalysisResponses];

export type CloudListCloudReportsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/cloud/reports';
};

export type CloudListCloudReportsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CloudListCloudReportsError = CloudListCloudReportsErrors[keyof CloudListCloudReportsErrors];

export type CloudListCloudReportsResponses = {
    /**
     * Successful Response
     */
    200: CloudAnalysisReportsPublic;
};

export type CloudListCloudReportsResponse = CloudListCloudReportsResponses[keyof CloudListCloudReportsResponses];

export type CloudGetCloudReportData = {
    body?: never;
    path: {
        /**
         * Report Id
         */
        report_id: string;
    };
    query?: never;
    url: '/api/v1/cloud/reports/{report_id}';
};

export type CloudGetCloudReportErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CloudGetCloudReportError = CloudGetCloudReportErrors[keyof CloudGetCloudReportErrors];

export type CloudGetCloudReportResponses = {
    /**
     * Successful Response
     */
    200: CloudAnalysisReportPublic;
};

export type CloudGetCloudReportResponse = CloudGetCloudReportResponses[keyof CloudGetCloudReportResponses];

export type CloudListCloudViolationsData = {
    body?: never;
    path: {
        /**
         * Report Id
         */
        report_id: string;
    };
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/cloud/reports/{report_id}/violations';
};

export type CloudListCloudViolationsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CloudListCloudViolationsError = CloudListCloudViolationsErrors[keyof CloudListCloudViolationsErrors];

export type CloudListCloudViolationsResponses = {
    /**
     * Successful Response
     */
    200: CloudViolationsPublic;
};

export type CloudListCloudViolationsResponse = CloudListCloudViolationsResponses[keyof CloudListCloudViolationsResponses];

export type CloudListCloudRulesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Platform
         */
        platform?: string | null;
    };
    url: '/api/v1/cloud/rules';
};

export type CloudListCloudRulesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CloudListCloudRulesError = CloudListCloudRulesErrors[keyof CloudListCloudRulesErrors];

export type CloudListCloudRulesResponses = {
    /**
     * Successful Response
     */
    200: CloudRulesPublic;
};

export type CloudListCloudRulesResponse = CloudListCloudRulesResponses[keyof CloudListCloudRulesResponses];

export type ScoringGetScoreData = {
    body?: never;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: never;
    url: '/api/v1/repositories/{repo_id}/score';
};

export type ScoringGetScoreErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScoringGetScoreError = ScoringGetScoreErrors[keyof ScoringGetScoreErrors];

export type ScoringGetScoreResponses = {
    /**
     * Successful Response
     */
    200: EnergyScorePublic;
};

export type ScoringGetScoreResponse = ScoringGetScoreResponses[keyof ScoringGetScoreResponses];

export type ScoringGetScoreHistoryData = {
    body?: never;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: {
        /**
         * Days
         */
        days?: number;
    };
    url: '/api/v1/repositories/{repo_id}/score/history';
};

export type ScoringGetScoreHistoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScoringGetScoreHistoryError = ScoringGetScoreHistoryErrors[keyof ScoringGetScoreHistoryErrors];

export type ScoringGetScoreHistoryResponses = {
    /**
     * Response Scoring-Get Score History
     * Successful Response
     */
    200: Array<ScoreHistoryPublic>;
};

export type ScoringGetScoreHistoryResponse = ScoringGetScoreHistoryResponses[keyof ScoringGetScoreHistoryResponses];

export type ScoringGetEnergyDetailData = {
    body?: never;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: never;
    url: '/api/v1/repositories/{repo_id}/energy';
};

export type ScoringGetEnergyDetailErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScoringGetEnergyDetailError = ScoringGetEnergyDetailErrors[keyof ScoringGetEnergyDetailErrors];

export type ScoringGetEnergyDetailResponses = {
    /**
     * Response Scoring-Get Energy Detail
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ScoringGetEnergyDetailResponse = ScoringGetEnergyDetailResponses[keyof ScoringGetEnergyDetailResponses];

export type AiGetCachedFixData = {
    body?: never;
    path: {
        /**
         * Violation Id
         */
        violation_id: string;
    };
    query?: never;
    url: '/api/v1/violations/{violation_id}/fix';
};

export type AiGetCachedFixErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AiGetCachedFixError = AiGetCachedFixErrors[keyof AiGetCachedFixErrors];

export type AiGetCachedFixResponses = {
    /**
     * Successful Response
     */
    200: AiFixSuggestionPublic;
};

export type AiGetCachedFixResponse = AiGetCachedFixResponses[keyof AiGetCachedFixResponses];

export type AiGetOrGenerateFixData = {
    body?: never;
    path: {
        /**
         * Violation Id
         */
        violation_id: string;
    };
    query?: {
        /**
         * Force
         * Set to true to regenerate even if a cached suggestion exists.
         */
        force?: boolean;
    };
    url: '/api/v1/violations/{violation_id}/fix';
};

export type AiGetOrGenerateFixErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AiGetOrGenerateFixError = AiGetOrGenerateFixErrors[keyof AiGetOrGenerateFixErrors];

export type AiGetOrGenerateFixResponses = {
    /**
     * Successful Response
     */
    200: AiFixSuggestionPublic;
};

export type AiGetOrGenerateFixResponse = AiGetOrGenerateFixResponses[keyof AiGetOrGenerateFixResponses];

export type AiFixAllViolationsData = {
    body?: never;
    path: {
        /**
         * Report Id
         */
        report_id: string;
    };
    query?: never;
    url: '/api/v1/reports/{report_id}/fix-all';
};

export type AiFixAllViolationsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AiFixAllViolationsError = AiFixAllViolationsErrors[keyof AiFixAllViolationsErrors];

export type AiFixAllViolationsResponses = {
    /**
     * Response Ai-Fix All Violations
     * Successful Response
     */
    202: {
        [key: string]: unknown;
    };
};

export type AiFixAllViolationsResponse = AiFixAllViolationsResponses[keyof AiFixAllViolationsResponses];

export type AiCreatePrFromReportData = {
    body?: never;
    path: {
        /**
         * Report Id
         */
        report_id: string;
    };
    query?: never;
    url: '/api/v1/reports/{report_id}/create-pr';
};

export type AiCreatePrFromReportErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AiCreatePrFromReportError = AiCreatePrFromReportErrors[keyof AiCreatePrFromReportErrors];

export type AiCreatePrFromReportResponses = {
    /**
     * Successful Response
     */
    201: VerdexPullRequestPublic;
};

export type AiCreatePrFromReportResponse = AiCreatePrFromReportResponses[keyof AiCreatePrFromReportResponses];

export type PublicGetPublicRepoProfileData = {
    body?: never;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Repo
         */
        repo: string;
    };
    query?: never;
    url: '/api/v1/public/repos/{owner}/{repo}';
};

export type PublicGetPublicRepoProfileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PublicGetPublicRepoProfileError = PublicGetPublicRepoProfileErrors[keyof PublicGetPublicRepoProfileErrors];

export type PublicGetPublicRepoProfileResponses = {
    /**
     * Response Public-Get Public Repo Profile
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type PublicGetPublicRepoProfileResponse = PublicGetPublicRepoProfileResponses[keyof PublicGetPublicRepoProfileResponses];

export type PublicGetLeaderboardData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Per Page
         */
        per_page?: number;
    };
    url: '/api/v1/public/leaderboard';
};

export type PublicGetLeaderboardErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PublicGetLeaderboardError = PublicGetLeaderboardErrors[keyof PublicGetLeaderboardErrors];

export type PublicGetLeaderboardResponses = {
    /**
     * Response Public-Get Leaderboard
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type PublicGetLeaderboardResponse = PublicGetLeaderboardResponses[keyof PublicGetLeaderboardResponses];

export type AdminTriggerFullRescanData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/rescan';
};

export type AdminTriggerFullRescanResponses = {
    /**
     * Response Admin-Trigger Full Rescan
     * Successful Response
     */
    202: {
        [key: string]: unknown;
    };
};

export type AdminTriggerFullRescanResponse = AdminTriggerFullRescanResponses[keyof AdminTriggerFullRescanResponses];

export type AdminGetSystemStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/stats';
};

export type AdminGetSystemStatsResponses = {
    /**
     * Response Admin-Get System Stats
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type AdminGetSystemStatsResponse = AdminGetSystemStatsResponses[keyof AdminGetSystemStatsResponses];

export type TelemetryListApiKeysData = {
    body?: never;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: never;
    url: '/api/v1/telemetry/repositories/{repo_id}/api-keys';
};

export type TelemetryListApiKeysErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TelemetryListApiKeysError = TelemetryListApiKeysErrors[keyof TelemetryListApiKeysErrors];

export type TelemetryListApiKeysResponses = {
    /**
     * Response Telemetry-List Api Keys
     * Successful Response
     */
    200: Array<RepositoryApiKeyPublic>;
};

export type TelemetryListApiKeysResponse = TelemetryListApiKeysResponses[keyof TelemetryListApiKeysResponses];

export type TelemetryCreateApiKeyData = {
    body: ApiKeyCreateIn;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: never;
    url: '/api/v1/telemetry/repositories/{repo_id}/api-keys';
};

export type TelemetryCreateApiKeyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TelemetryCreateApiKeyError = TelemetryCreateApiKeyErrors[keyof TelemetryCreateApiKeyErrors];

export type TelemetryCreateApiKeyResponses = {
    /**
     * Successful Response
     */
    201: ApiKeyCreatedOut;
};

export type TelemetryCreateApiKeyResponse = TelemetryCreateApiKeyResponses[keyof TelemetryCreateApiKeyResponses];

export type TelemetryRevokeApiKeyData = {
    body?: never;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
        /**
         * Key Id
         */
        key_id: string;
    };
    query?: never;
    url: '/api/v1/telemetry/repositories/{repo_id}/api-keys/{key_id}';
};

export type TelemetryRevokeApiKeyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TelemetryRevokeApiKeyError = TelemetryRevokeApiKeyErrors[keyof TelemetryRevokeApiKeyErrors];

export type TelemetryRevokeApiKeyResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type TelemetryRevokeApiKeyResponse = TelemetryRevokeApiKeyResponses[keyof TelemetryRevokeApiKeyResponses];

export type TelemetryIngestTelemetryData = {
    body: TelemetryPayload;
    headers: {
        /**
         * X-Verdex-Api-Key
         */
        'X-Verdex-Api-Key': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/telemetry/ingest';
};

export type TelemetryIngestTelemetryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TelemetryIngestTelemetryError = TelemetryIngestTelemetryErrors[keyof TelemetryIngestTelemetryErrors];

export type TelemetryIngestTelemetryResponses = {
    /**
     * Response Telemetry-Ingest Telemetry
     * Successful Response
     */
    202: {
        [key: string]: unknown;
    };
};

export type TelemetryIngestTelemetryResponse = TelemetryIngestTelemetryResponses[keyof TelemetryIngestTelemetryResponses];

export type TelemetryListTelemetryData = {
    body?: never;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/telemetry/repositories/{repo_id}/data';
};

export type TelemetryListTelemetryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TelemetryListTelemetryError = TelemetryListTelemetryErrors[keyof TelemetryListTelemetryErrors];

export type TelemetryListTelemetryResponses = {
    /**
     * Response Telemetry-List Telemetry
     * Successful Response
     */
    200: Array<TelemetryDataPointPublic>;
};

export type TelemetryListTelemetryResponse = TelemetryListTelemetryResponses[keyof TelemetryListTelemetryResponses];

export type OrganizationsListOrganizationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/organizations';
};

export type OrganizationsListOrganizationsResponses = {
    /**
     * Response Organizations-List Organizations
     * Successful Response
     */
    200: Array<OrganizationPublic>;
};

export type OrganizationsListOrganizationsResponse = OrganizationsListOrganizationsResponses[keyof OrganizationsListOrganizationsResponses];

export type OrganizationsCreateOrganizationData = {
    body: OrgCreateIn;
    path?: never;
    query?: never;
    url: '/api/v1/organizations';
};

export type OrganizationsCreateOrganizationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OrganizationsCreateOrganizationError = OrganizationsCreateOrganizationErrors[keyof OrganizationsCreateOrganizationErrors];

export type OrganizationsCreateOrganizationResponses = {
    /**
     * Successful Response
     */
    201: OrganizationPublic;
};

export type OrganizationsCreateOrganizationResponse = OrganizationsCreateOrganizationResponses[keyof OrganizationsCreateOrganizationResponses];

export type OrganizationsDeleteOrganizationData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/v1/organizations/{slug}';
};

export type OrganizationsDeleteOrganizationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OrganizationsDeleteOrganizationError = OrganizationsDeleteOrganizationErrors[keyof OrganizationsDeleteOrganizationErrors];

export type OrganizationsDeleteOrganizationResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type OrganizationsDeleteOrganizationResponse = OrganizationsDeleteOrganizationResponses[keyof OrganizationsDeleteOrganizationResponses];

export type OrganizationsGetOrganizationData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/v1/organizations/{slug}';
};

export type OrganizationsGetOrganizationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OrganizationsGetOrganizationError = OrganizationsGetOrganizationErrors[keyof OrganizationsGetOrganizationErrors];

export type OrganizationsGetOrganizationResponses = {
    /**
     * Successful Response
     */
    200: OrganizationPublic;
};

export type OrganizationsGetOrganizationResponse = OrganizationsGetOrganizationResponses[keyof OrganizationsGetOrganizationResponses];

export type OrganizationsListMembersData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/v1/organizations/{slug}/members';
};

export type OrganizationsListMembersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OrganizationsListMembersError = OrganizationsListMembersErrors[keyof OrganizationsListMembersErrors];

export type OrganizationsListMembersResponses = {
    /**
     * Response Organizations-List Members
     * Successful Response
     */
    200: Array<OrganizationMemberPublic>;
};

export type OrganizationsListMembersResponse = OrganizationsListMembersResponses[keyof OrganizationsListMembersResponses];

export type OrganizationsAddMemberData = {
    body: MemberAddIn;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/v1/organizations/{slug}/members';
};

export type OrganizationsAddMemberErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OrganizationsAddMemberError = OrganizationsAddMemberErrors[keyof OrganizationsAddMemberErrors];

export type OrganizationsAddMemberResponses = {
    /**
     * Successful Response
     */
    201: OrganizationMemberPublic;
};

export type OrganizationsAddMemberResponse = OrganizationsAddMemberResponses[keyof OrganizationsAddMemberResponses];

export type OrganizationsRemoveMemberData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{slug}/members/{user_id}';
};

export type OrganizationsRemoveMemberErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OrganizationsRemoveMemberError = OrganizationsRemoveMemberErrors[keyof OrganizationsRemoveMemberErrors];

export type OrganizationsRemoveMemberResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type OrganizationsRemoveMemberResponse = OrganizationsRemoveMemberResponses[keyof OrganizationsRemoveMemberResponses];

export type OrganizationsListAuditLogsData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Action
         */
        action?: string | null;
    };
    url: '/api/v1/organizations/{slug}/audit-logs';
};

export type OrganizationsListAuditLogsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OrganizationsListAuditLogsError = OrganizationsListAuditLogsErrors[keyof OrganizationsListAuditLogsErrors];

export type OrganizationsListAuditLogsResponses = {
    /**
     * Response Organizations-List Audit Logs
     * Successful Response
     */
    200: Array<AuditLogPublic>;
};

export type OrganizationsListAuditLogsResponse = OrganizationsListAuditLogsResponses[keyof OrganizationsListAuditLogsResponses];

export type OutreachOptOutData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Repo
         * Repository to opt out in 'owner/repo' format.
         */
        repo: string;
    };
    url: '/api/v1/opt-out';
};

export type OutreachOptOutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OutreachOptOutError = OutreachOptOutErrors[keyof OutreachOptOutErrors];

export type OutreachOptOutResponses = {
    /**
     * Response Outreach-Opt Out
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type OutreachOptOutResponse = OutreachOptOutResponses[keyof OutreachOptOutResponses];

export type OutreachSubmitOssFixRequestData = {
    body: OssFixRequestIn;
    path?: never;
    query?: never;
    url: '/api/v1/oss/fix-requests';
};

export type OutreachSubmitOssFixRequestErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OutreachSubmitOssFixRequestError = OutreachSubmitOssFixRequestErrors[keyof OutreachSubmitOssFixRequestErrors];

export type OutreachSubmitOssFixRequestResponses = {
    /**
     * Successful Response
     */
    201: OssFixRequestPublic;
};

export type OutreachSubmitOssFixRequestResponse = OutreachSubmitOssFixRequestResponses[keyof OutreachSubmitOssFixRequestResponses];

export type OutreachGetOssFixRequestData = {
    body?: never;
    path: {
        /**
         * Request Id
         */
        request_id: string;
    };
    query?: never;
    url: '/api/v1/oss/fix-requests/{request_id}';
};

export type OutreachGetOssFixRequestErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OutreachGetOssFixRequestError = OutreachGetOssFixRequestErrors[keyof OutreachGetOssFixRequestErrors];

export type OutreachGetOssFixRequestResponses = {
    /**
     * Successful Response
     */
    200: OssFixRequestPublic;
};

export type OutreachGetOssFixRequestResponse = OutreachGetOssFixRequestResponses[keyof OutreachGetOssFixRequestResponses];

export type PrivateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type PrivateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PrivateCreateUserError = PrivateCreateUserErrors[keyof PrivateCreateUserErrors];

export type PrivateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type PrivateCreateUserResponse = PrivateCreateUserResponses[keyof PrivateCreateUserResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};
